name: Trigger Intelligence

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  trigger-intelligence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Commit Message
        run: echo "Triggering intelligence with the latest commit."
